// Generated by CoffeeScript 1.3.3
var DistrictMap, GeoReceiver, MapControls, MapData, MapStyle, get_location, server_url, show_position,
  _this = this;

server_url = "http://localhost:8000";

$(document).ready(function() {
  GeoReceiver.init();
  return $('button').click(function() {
    return MapControls.toggle_district_layer();
  });
});

DistrictMap = {
  map: void 0,
  district_layer: void 0,
  initialize: function() {
    var osm_layer;
    this.map = new OpenLayers.Map({
      div: 'map',
      projection: new OpenLayers.Projection('EPSG:900313')
    });
    osm_layer = new OpenLayers.Layer.OSM();
    this.map.addLayer(osm_layer);
    this.add_district_layer();
    return get_location();
  },
  center_map: function(center_x, center_y) {
    return this.map.setCenter((new OpenLayers.LonLat(center_x, center_y)).transform("EPSG:4326", "EPSG:900913"), 8);
  },
  add_district_layer: function() {
    this.district_layer = new OpenLayers.Layer.Vector("Berlin Districts", {
      projection: new OpenLayers.Projection('EPSG:900313')
    });
    this.district_layer.removeAllFeatures();
    this.district_layer.addFeatures(MapData.district_features());
    return this.map.addLayer(this.district_layer);
  }
};

MapData = {
  map_data: [],
  weighted: false,
  district_features: function() {
    var district, features, geojson_parser, geojson_polygon, relevant_count, style, _i, _len, _ref;
    relevant_count = (this.weighted ? 'weighted_count' : 'count');
    geojson_parser = new OpenLayers.Format.GeoJSON;
    features = [];
    _ref = this.map_data;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      district = _ref[_i];
      style = MapStyle.style(0);
      geojson_polygon = geojson_parser.read(district['area']);
      geojson_polygon.style = style;
      features.push(geojson_polygon);
    }
    return features;
  },
  district_color: function(count) {
    var colors, i, quantil, _i, _len, _ref;
    colors = ['#00ff00', '#ffff00', '#df7401', '#df0101'];
    i = 0;
    _ref = this.quantils();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      quantil = _ref[_i];
      if (count < quantil) {
        break;
      }
      i++;
    }
    return colors[i];
  },
  quantils: function() {
    if (this.weighted) {
      return [5];
    } else {
      return [5];
    }
  }
};

MapStyle = {
  renderer: function() {
    var renderer;
    return renderer = OpenLayers.Layer.Vector.prototype.renderers;
  },
  layer_style: function() {
    var layer_style;
    layer_style = OpenLayers.Util.extend({}, OpenLayers.Feature.Vector.style['default']);
    layer_style.fillOpacity = 0.8;
    layer_style.graphicOpacity = 1;
    return layer_style;
  },
  style: function(color) {
    var style;
    style = OpenLayers.Util.extend({}, this.layer_style());
    style.strokeColor = 'red';
    style.fillColor = 'red';
    return style;
  }
};

MapControls = {
  toggle_district_layer: function() {
    var button;
    button = $('#button');
    if (button.text() === "Change to Weighted") {
      MapData.weighted = true;
      button.text('Change to Normal');
    } else {
      MapData.weighted = false;
      button.text('Change to Weighted');
    }
    return DistrictMap.add_district_layer();
  },
  update_legend: function() {
    var i, quantil, quantils, _i, _len;
    i = 0;
    quantils = MapData.quantils();
    for (_i = 0, _len = quantils.length; _i < _len; _i++) {
      quantil = quantils[_i];
      $("#quantil" + i).text("less than " + quantil);
      i++;
    }
    return $("#quantil3").text("greater than or equal to " + quantils[2]);
  }
};

get_location = function() {
  if (navigator.geolocation) {
    return navigator.geolocation.getCurrentPosition(show_position);
  }
};

show_position = function(position) {
  return DistrictMap.center_map(position.coords.longitude, position.coords.latitude);
};

GeoReceiver = {
  init: function() {
    var settings;
    settings = {
      dataType: 'jsonp',
      url: "" + server_url + "/api/v1/communities/?state__name=Berlin",
      success: GeoReceiver.process_districts
    };
    return $.ajax(settings);
  },
  process_districts: function(data) {
    MapData.map_data = data['objects'];
    return DistrictMap.initialize();
  }
};
