// Generated by CoffeeScript 1.4.0
(function() {
  var DistrictMap, GeoReceiver, MapData, MapStyle, configuration, epsg4326, epsg900913,
    _this = this;

  configuration = {
    server_url: "http://localhost:8000",
    rest_resource: "api/v1/hotspots/",
    geo_attribute_name: "location",
    object_color: '#0000ff',
    container_attribute_name: "objects",
    center_x: 13.4,
    center_y: 52.5
  };

  epsg4326 = new OpenLayers.Projection('EPSG:4326');

  epsg900913 = new OpenLayers.Projection('EPSG:900913');

  DistrictMap = {
    map: null,
    data_layer: null,
    initialize: function() {
      var layer;
      this.map = new OpenLayers.Map('map', {
        projection: epsg900913,
        displayProjection: epsg4326
      });
      layer = new OpenLayers.Layer.OSM();
      this.map.addLayer(layer);
      this.add_data_layer();
      return this.center_map(configuration.center_x, configuration.center_y);
    },
    center_map: function(center_x, center_y) {
      return this.map.setCenter((new OpenLayers.LonLat(center_x, center_y)).transform("EPSG:4326", "EPSG:900913"), 10);
    },
    add_data_layer: function() {
      var features;
      this.data_layer = new OpenLayers.Layer.Vector("Map Data");
      this.data_layer.removeAllFeatures();
      features = MapData.data_feature_collection();
      this.data_layer.addFeatures(features);
      return this.map.addLayer(this.data_layer);
    }
  };

  MapData = {
    map_data: [],
    data_feature_collection: function() {
      var district, feature, featurecollection, geojson_format, style, _i, _len, _ref;
      featurecollection = [];
      geojson_format = new OpenLayers.Format.GeoJSON();
      _ref = this.map_data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        district = _ref[_i];
        feature = {
          "geometry": null,
          "type": "Feature",
          "properties": {}
        };
        style = MapStyle.style(configuration.object_color);
        feature.geometry = district[configuration.geo_attribute_name];
        feature = geojson_format.parseFeature(feature);
        feature.style = style;
        featurecollection.push(feature);
      }
      return featurecollection;
    }
  };

  MapStyle = {
    renderer: function() {
      var renderer;
      return renderer = OpenLayers.Layer.Vector.prototype.renderers;
    },
    layer_style: function() {
      var layer_style;
      layer_style = OpenLayers.Util.extend({}, OpenLayers.Feature.Vector.style['default']);
      layer_style.fillOpacity = 0.4;
      layer_style.graphicOpacity = 1;
      return layer_style;
    },
    style: function(color) {
      var style;
      style = OpenLayers.Util.extend({}, this.layer_style());
      style.strokeColor = color;
      style.fillColor = color;
      style.pointRadius = 15;
      return style;
    }
  };

  GeoReceiver = {
    init: function() {
      var settings;
      settings = {
        dataType: 'jsonp',
        url: "" + configuration.server_url + "/" + configuration.rest_resource,
        success: GeoReceiver.process_data
      };
      return $.ajax(settings);
    },
    process_data: function(data) {
      var settings;
      MapData.map_data = MapData.map_data.concat(data[configuration.container_attribute_name]);
      if (data.meta.next != null) {
        settings = {
          dataType: 'jsonp',
          url: configuration.server_url + data.meta.next,
          success: GeoReceiver.process_data
        };
        return $.ajax(settings);
      } else {
        return DistrictMap.initialize();
      }
    }
  };

  jQuery(function() {
    return GeoReceiver.init();
  });

}).call(this);
