// Generated by CoffeeScript 1.4.0
var MapStyle, OsmHeatMap;

OsmHeatMap = {
  map: null,
  initialize: function() {
    var epsg4326, epsg900913, report, _i, _len, _ref;
    if (this.map !== null) {
      return;
    }
    epsg4326 = new OpenLayers.Projection('EPSG:4326');
    epsg900913 = new OpenLayers.Projection('EPSG:900913');
    this.map = new OpenLayers.Map('heat_map');
    this.layer = new OpenLayers.Layer.OSM();
    this.crime_data = {
      max: 1,
      data: []
    };
    _ref = ReportReceiver.reports;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      report = _ref[_i];
      if (report.location.type === "Point") {
        this.crime_data.data.push({
          count: 1,
          lonlat: new OpenLayers.LonLat(report.location.coordinates[0], report.location.coordinates[1]).transform(epsg900913, epsg4326)
        });
      }
    }
    this.heatmap = new OpenLayers.Layer.Heatmap("Heatmap Layer", this.map, this.layer, {
      visible: true,
      radius: 5
    }, {
      isBaseLayer: false,
      opacity: 0.3,
      projection: new OpenLayers.Projection("EPSG:4326")
    });
    this.map.addLayers([this.layer, this.heatmap]);
    this.map.setCenter(new OpenLayers.LonLat(13.5, 52.5).transform(epsg4326, epsg900913), 9);
    return this.heatmap.setDataSet(this.crime_data);
  }
};

MapStyle = {
  renderer: function() {
    var renderer;
    renderer = OpenLayers.Util.getParameters(window.location.href).renderer;
    return renderer = (renderer ? [renderer] : OpenLayers.Layer.Vector.prototype.renderers);
  },
  layer_style: function() {
    var layer_style;
    layer_style = OpenLayers.Util.extend({}, OpenLayers.Feature.Vector.style['default']);
    layer_style.fillOpacity = 0.3;
    layer_style.graphicOpacity = 1;
    return layer_style;
  },
  style: function(color) {
    var style;
    style = OpenLayers.Util.extend({}, this.layer_style());
    style.strokeColor = color;
    style.fillColor = color;
    return style;
  }
};
