// Generated by CoffeeScript 1.3.3
var MapStyle, OsmHeatMap;

OsmHeatMap = {
  map: void 0,
  initialize: function() {
    var crime_data, epsg4326, epsg900913, heatmap, layer, report, x, _i, _j, _len, _ref;
    epsg4326 = new OpenLayers.Projection('EPSG:4326');
    epsg900913 = new OpenLayers.Projection('EPSG:900913');
    this.map = new OpenLayers.Map('heat_map');
    layer = new OpenLayers.Layer.OSM();
    crime_data = {
      max: 10,
      data: []
    };
    _ref = ReportReceiver.reports;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      report = _ref[_i];
      for (x = _j = 0; _j <= 10; x = ++_j) {
        crime_data.data.push({
          count: 1,
          lonlat: new OpenLayers.LonLat(report.location.coordinates[0], report.location.coordinates[1]).transform(epsg900913, epsg4326)
        });
      }
    }
    heatmap = new OpenLayers.Layer.Heatmap("Heatmap Layer", this.map, layer, {
      visible: true,
      radius: 5
    }, {
      isBaseLayer: false,
      opacity: 0.3,
      projection: new OpenLayers.Projection("EPSG:4326")
    });
    this.map.addLayers([layer, heatmap]);
    return heatmap.setDataSet(crime_data);
  }
};

MapStyle = {
  renderer: function() {
    var renderer;
    renderer = OpenLayers.Util.getParameters(window.location.href).renderer;
    return renderer = (renderer ? [renderer] : OpenLayers.Layer.Vector.prototype.renderers);
  },
  layer_style: function() {
    var layer_style;
    layer_style = OpenLayers.Util.extend({}, OpenLayers.Feature.Vector.style['default']);
    layer_style.fillOpacity = 0.3;
    layer_style.graphicOpacity = 1;
    return layer_style;
  },
  style: function(color) {
    var style;
    style = OpenLayers.Util.extend({}, this.layer_style());
    style.strokeColor = color;
    style.fillColor = color;
    return style;
  }
};
