// Generated by CoffeeScript 1.3.3
var init_heat_map;

init_heat_map = function() {
  return OsmHeatMap.initialize();
};

$('#heat_link').click(function() {
  return setTimeout(init_heat_map, 100);
});
